version: '3.1'

services:
  database:
    image: mariadb:10.5
    restart: always
    environment:
      MARIADB_DATABASE: wpdb
      MARIADB_USER: wp_user
      MARIADB_PASSWORD: bE9UabWw7rEQJZTq
      MARIADB_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - database:/var/lib/mysql

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 80:80
    depends_on:
      - database
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: bE9UabWw7rEQJZTq
      WORDPRESS_DB_NAME: wpdb
    volumes:
      - wordpress:/var/www/html

volumes:
  wordpress:
  database: